version: '3.7'
services:
  discord-power-bot:
    image: ghcr.io/kharms-dev/discord-power-bot:latest
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - servers.json:/home/appuser/servers.json