name: 1Password Secrets Test

on:
  workflow_dispatch: {}

env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        run: |
          curl https://cache.agilebits.com/dist/1P/op2/pkg/v2.8.0-beta.05/op_linux_amd64_v2.8.0-beta.05.zip--output op_cli.pkg
          sudo installer -pkg op_cli.pkg -target ~
      - name: Read Field from 1Password
        run: op read "op://Kharms Dev/Test Secret/password"