name: 1Password Secrets Test

on:
  workflow_dispatch: {}

env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        run: |
          wget https://cache.agilebits.com/dist/1P/op2/pkg/v2.8.0-beta.05/op_linux_amd64_v2.8.0-beta.05.zip -O op.zip && \
          unzip -d op op.zip && \
          sudo mv op/op /usr/local/bin && \
          rm -r op.zip op

      - name: Read Field from 1Password
        run: op read "op://Kharms Dev/Test Secret/password"