name: Release

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Build image tag
        run: echo "IMAGE_TAG=$(git log -1 --pretty=%h)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kharms-dev/discord-power-bot:${{ env.IMAGE_TAG }}
            ghcr.io/kharms-dev/discord-power-bot:latest
          file: ./Dockerfile
          build-args: |
            IMAGE_TAG=${{ env.IMAGE_TAG }}
